### ISSUE TITLE
This button seems to not be doing anything?

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#104]
![image](https://github.com/uNotesOfficial/upup/assets/43147238/55b4c670-87ed-4d36-bc25-172f653bbee2)

**Comment by MohamedBechirMejri** [comment]
@AminDhouib this was added when I was remaking the UI to follow uppy's. it's supposed to show an image editor.

I'm almost finished with the file browser. I can start working on the editor or we can hide the icon and implement it after release if there are more important tasks

**Comment by AminDhouib** [comment]
Hide it and let's implement it after uNotes release :)
