### ISSUE TITLE
Upup does not behave well when uploading more than 3 files

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#107]
Upup component gets smaller if more than 3 files are in the process of being uploaded

![image](https://github.com/uNotesOfficial/upup/assets/43147238/034f5d23-899d-4650-8c82-d9af8f42c88e)

**Comment by MohamedBechirMejri** [comment]
@AminDhouib as discussed in [#628](https://github.com/uNotesOfficial/unotes-next/issues/628) , we've added a limit prop to upup so users don't abuse the service. in unotes it's currently set to 5 so upup will filter any additional files you select and only use the last 5. we can bump the files limit in unotes if you want and I also recommend we add a note for users that they can't  upload more than x number of files

as for the UI breaking I will check it out and fix it ;)

**Comment by AminDhouib** [comment]
Yes! I realized that and I changed the description of the issue before you made that comment above. Sorry about that @MohamedBechirMejri .

But yeah fix that UI issue though please :)
