### ISSUE TITLE
Hide Unsupported "files" when attempting to upload things in GDrive

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#142]
When attempting to showcase the gdrive files, we shouldn't be showing files that are not "uploadale" (aka google sheets, google docs, google slides...)

**Comment by AminDhouib** [comment]
Reopening this issue. I still see GDrive "files" i shouldnt be seeing. 

These are all Google Doc files
![image](https://github.com/uNotesOfficial/upup/assets/43147238/bdc3f2a1-c2d0-406a-9028-c8bc8bc40538)

**Comment by AminDhouib** [comment]
Status on this issue? @bassem97 @MohamedBechirMejri
I believe this is done right?

**Comment by MohamedBechirMejri** [comment]
I think so. can you try again and see if it got fixed ? 
if not can you tell us how to reproduce the issue ?
