### ISSUE TITLE
Visualize The Progress Of The Files Being Uploaded 

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#147]
When we are uploading multiple files or uploading very large files (or if internet connection is slow), the user has no idea what is going on.

It should show which file are currently being uploaded and should show a % progress bar. 

Use this perhaps to get the progression bar: https://stackoverflow.com/questions/76209007/get-continous-progress-on-upload-to-aws-digital-ocean-spaces-using-javascript-sd

Please when working on this task test it with these circumstances:
- Upload 1 file
- Upload multiple files
- Upload a large file
- Upload multiple large files

Progress can be shown right here:
![image](https://github.com/uNotesOfficial/upup/assets/43147238/84046515-2629-4f4f-8ca5-008b4cf0134f)

Similar to how it is in Uppy:
![image](https://github.com/uNotesOfficial/upup/assets/43147238/195b071f-8a8d-4862-ab58-9318abae83d8)

**Comment by yaakoubiIheb** [comment]
done

**Comment by MohamedBechirMejri** [comment]
> done

are you sure ? we need to show the file upload progress (we get it from aws) not the doc upload progress like in unotes

**Comment by yaakoubiIheb** [comment]
Ah. Okay
