### ISSUE TITLE
Selecting Files in Picker Is Buggy

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#176]
https://github.com/uNotesOfficial/upup/assets/43147238/b416a9fb-d3e9-4cb8-9e5a-2c3c54b83a19

**Comment by MohamedBechirMejri** [comment]
yup will need to fix that. funny thing is it was working fine but the build breaks for some reason so we had to sacrifice the animation to be able to build

**Comment by AminDhouib** [comment]
That is interesting haha! @MohamedBechirMejri
