### ISSUE TITLE
Add Spinner after "Add X Files" has been clicked from Picker

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#178]
After clicking that button, there is a delay that occurs (to load). Add a spinner there and hide the button to indicate that the component is loading.
![image](https://github.com/uNotesOfficial/upup/assets/43147238/1b583120-d57b-49b8-8947-db12890723b5)

**Comment by maheshchandra10** [comment]
Please check my PR for this issue, along with this comment- https://github.com/uNotesOfficial/upup/pull/181#issuecomment-1780715449
