### ISSUE TITLE
File Restrictions Should Be Displayed Within Upup

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#180]
![image](https://github.com/uNotesOfficial/upup/assets/43147238/0e72d522-45a2-4248-a6fb-5bb512234ef2)

Similarly, how it is done here:
![image](https://github.com/uNotesOfficial/upup/assets/43147238/454ad1b9-6786-40bd-941c-2551b0a5e43e)

**Comment by MohamedBechirMejri** [comment]
should we add a size restriction too ? @AminDhouib

**Comment by AminDhouib** [comment]
@MohamedBechirMejri oh yes that's not implemented. Make a separate issue on it and link the issue here.

**Comment by MohamedBechirMejri** [comment]
#182
