### ISSUE TITLE
No way to properly switch between Google Accounts 

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#214]
User's needs to refresh the component (or page) to use a different account. There should be a way for users to switch Google accounts from the Upup component.

**Comment by bassem97** [comment]
@AminDhouib Yup the process of google logout is kinda buggy

**Comment by AminDhouib** [comment]
@bassem97 yup got to fix that so that the devs loves using the upup app :)

**Comment by MohamedBechirMejri** [comment]
![chrome_WSf4mUJzPF](https://github.com/uNotesOfficial/upup/assets/76930306/df7befa7-1ba5-4e5f-a08f-de5d5af02934)

it seems to work fine, can you guys tell me what needs fixing exactly ?

**Comment by bassem97** [comment]
> ![chrome_WSf4mUJzPF](https://github.com/uNotesOfficial/upup/assets/76930306/df7befa7-1ba5-4e5f-a08f-de5d5af02934)
> 
> it seems to work fine, can you guys tell me what needs fixing exactly ?

@MohamedBechirMejri that was on storybook ? If so try to do same thing on unotes.net

**Comment by MohamedBechirMejri** [comment]
ah i will check it out then ;)
