### ISSUE TITLE
OneDrive integration does not seem to work

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#215]
![image](https://github.com/uNotesOfficial/upup/assets/43147238/681e26df-dc06-430c-b215-8599965608e7)

**Comment by MohamedBechirMejri** [comment]
![image](https://github.com/uNotesOfficial/upup/assets/76930306/df062487-d912-4738-9363-a07d0b24256c)

seems to be working for me

**Comment by bassem97** [comment]
> ![image](https://github.com/uNotesOfficial/upup/assets/43147238/681e26df-dc06-430c-b215-8599965608e7)
> 

How can we reproduce that bug @Amin-Dhouib ?

**Comment by AminDhouib** [comment]
Try to use the amin.dhouib.pro@outlook.com email. It does not work for me on dev.unotes.net
(I will send the password to you in private)

@MohamedBechirMejri @bassem97

**Comment by bassem97** [comment]
@AminDhouib that's weird actually xD, @MohamedBechirMejri take a look

**Comment by bassem97** [comment]
@AminDhouib it doesn't work only with your account ahhah xD

**Comment by bassem97** [comment]
@AminDhouib @MohamedBechirMejri the problem is we don't really use that much outlook account, so we had to test this feature only with the default account no-reply-unotes@outlook.com, so bad i implemented the feature by testing it only with that account
