### ISSUE TITLE
GDrive Picker Appears But Files Do Not Seem To be Shown

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#28]
When loading a file from the driver picker, it does not seem to show the file that is about to be uploaded. I selected a PDF file from my GDrive Picker but nothing shows as selected:

![image](https://github.com/uNotesOfficial/upup/assets/43147238/6568766d-70b3-4d34-af96-33f69e016155)

**Comment by bassem97** [comment]
@AminDhouib  actually yeah it doesn't show there but if you fill the inputs and upload, it will be uploaded , this is a little fix that can affect the relation between uploadFiles & googledrive and onedrive components , so i need to divide this into a smaller issues

**Comment by AminDhouib** [comment]
Yeah fair enough, feel free to do what it needed!
