### ISSUE TITLE
UI Overhaul - Part 3 

### ISSUE THREAD

**Issue by arijhajji-1** [DevinoSolutions/upup#61]
Adopting a unified picker UI for different integrations, similar to Uppy's approach, could lead to a cleaner and more consistent user interface across our various integration points. This alignment in UI design could contribute to a more seamless user experience and help streamline interactions within the Upup platform.

![image](https://github.com/uNotesOfficial/upup/assets/61475226/72965041-c2b7-4963-bb84-374a5ead5873)

**Comment by AminDhouib** [comment]
Great idea but I dont think for the time being it would be a good idea to implement it since its pretty complex, we might want to look into it after release.

**Comment by AminDhouib** [comment]
Given the speed we are going at, I think we can squeeze this feature for release. @bassem97 get us started with this. Do not worry too much about how pretty the UI looks, @MohamedBechirMejri can help us out on that a little later

**Comment by bassem97** [comment]
@AminDhouib  Roger that

**Comment by AminDhouib** [comment]
@MohamedBechirMejri resume this please, I would really like this polish to be integrated into upup :)

**Comment by MohamedBechirMejri** [comment]
I've done a lot of work on this but now I have two problems that I need help with 

first: google's api sometimes refuses the request for the previews. 
![image](https://github.com/uNotesOfficial/upup/assets/76930306/503c1e14-c5e4-4038-a131-ce3f6f0867dd)

it's unreliable sometimes it works fine sometimes it doesn't. other people say it only happens on localhost but I haven't tested that yet.

Second: this is a very weird bug. when I try to build I get this error:
![image](https://github.com/uNotesOfficial/upup/assets/76930306/1269a122-c412-490e-a748-41023cbb4089)

TypeError: base$1[type] is not a function

I couldn't find a solution for this anywhere and I don't get any errors in storybook.

@bassem97 if we can fix this then we can close this issue everything else is done
