### ISSUE TITLE
Upup Integrations take too long to process when big files are submitted

### ISSUE THREAD

**Issue by AminDhouib** [DevinoSolutions/upup#99]

**Comment by MohamedBechirMejri** [comment]
Can you provide more details ?

**Comment by AminDhouib** [comment]
Ah my apologies!
So, take any file from google drive or from onedrive that is pretty large (say 100MBs or higher). You will notice that it seems like nothing is loading / happening but give it some time and your file will finally appear on the UpUp selection.

**Comment by bassem97** [comment]
@AminDhouib yes we need to add loader when uploading

**Comment by AminDhouib** [comment]
Status on this issue? @bassem97  @MohamedBechirMejri

**Comment by bassem97** [comment]
@AminDhouib Actually that depends on your upload speed because we are handling the upload in the browser not on hosted server

**Comment by bassem97** [comment]
[screen-capture.webm](https://github.com/uNotesOfficial/upup/assets/36534106/897e672d-377e-44b7-9f08-2ae6cf161880)

**Comment by bassem97** [comment]
![image](https://github.com/uNotesOfficial/upup/assets/36534106/a2df9953-e1fc-4459-845c-7a38d964d1ab)

**Comment by AminDhouib** [comment]
Yup! Precisely. We added the progress bar which pretty much "fixes" the concern. Closing the issue. Thanks @bassem97 just wanted to confirm.
